### ISSUE TITLE
hexo-filter-optimize cause Valine comments not work

### ISSUE THREAD

**Issue by nankingcigar** [theme-next/hexo-filter-optimize#14]
Hi,
When I use hexo-filter-optimize, even js code run     new Valine({
        el: '#comments' ,
        verify: {{ theme.valine.verify }},
        notify: {{ theme.valine.notify }},
        appId: '{{ theme.valine.appid }}',
        appKey: '{{ theme.valine.appkey }}',
        placeholder: '{{ theme.valine.placeholder }}',
        avatar:'{{ theme.valine.avatar }}',
        guest_info:guest,
        pageSize:'{{ theme.valine.pageSize }}' || 10,
    }); but the comments element doesn't show. Console no errors.
Anyone know how to let it works?

**Comment by stevenjoezhang** [comment]
See also https://github.com/theme-next/hexo-filter-optimize/issues/7

**Comment by stevenjoezhang** [comment]
Should be fixed in version 0.2.7
