### ISSUE TITLE
CSS filter causes icons to disappear in Muses

### ISSUE THREAD

**Issue by maddovr** [theme-next/hexo-filter-optimize#4]
Enabling the option:
css:
    enable: true
Makes FontAwesome icons disappear when deployed to netlify, alright locally(probably due to the fact I have it installed). NeXT 6.0.3, Muses scheme

Screenshot of the problem: https://abload.de/img/2018-01-31-14-06-5a71a4pzz.png

**Comment by tsanie** [comment]
probably similar with #2 , the `font-awesome.css` uses font files in a relative way, but the bundled `style.css` breaks the relation path.
- try to use a cdn FontAwesome
- manual change the `src` in the `font-awesome.css` file
- add `font-awesome.css` in the `css.excludes` (not recommends)

**Comment by maddovr** [comment]
How to set the first option? Tried
`fontawesome: https://use.fontawesome.com/releases/v5.0.6/css/all.css`
Which is the recommended CDN but the issue is still present.

**Comment by tsanie** [comment]
Please try the 4.x version, 5.x font-awesome seems not support now.

just try set it to `https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css`

**Comment by maddovr** [comment]
It worked, however since we're on the issue(and it should be the same), the needMoreShare button(internal) is also bugged(it only shows the color but not the icons.
Screenshot: https://abload.de/img/2018-01-31-14-48-www.dqk7c.png

**Comment by tsanie** [comment]
Yes, I find the [`needsharebutton.css`](https://github.com/theme-next/theme-next-needmoreshare2/blob/master/needsharebutton.css#L9) of needMoreShare use a `@import` to link the another file `font-embedded.css`, that would also cause this problem.

---

emmm, actually you can just copy all content of the `font-embedded.css` into the top of  `needsharebutton.css` and then remove its `@import` line. (_It is the temporary solution_)

**Comment by tsanie** [comment]
I'll close this issue, if there is still a problem with it, you can reopen it later.
