### ISSUE TITLE
很棒！但对本地调试不太友好……

### ISSUE THREAD

**Issue by reuixiy** [theme-next/hexo-filter-optimize#5]
本地`hexo s`调试时，与没有安装前相比，反应太慢，消耗了太多的 CPU 和内存，不太友好。

能否作为一个单独功能？

比如用一个新的命令`hexo optimize`，这样每次 deploy 前执行一下`hexo optimize`即可，不会影响本地调试。

**Comment by daya0576** [comment]
me too, any solution??

**Comment by reuixiy** [comment]
Just modify `true` to `false` in _config.yml when you run `hexo s`, and modify `false` to `true` before you plan to `deploy` it to GitHub Pages. :joy_cat:

**Comment by daya0576** [comment]
> Just modify `true` to `false` in _config.yml when you run `hexo s`, and modify `false` to `true` before you plan to `deploy` it to GitHub Pages. 😹

```bash
open_filter_optimize="enable: true # filter_optimize"
close_filter_optimize="enable: false # filter_optimize"
# 开启filter_optimize
sed -i "" "s/$close_filter_optimize/$open_filter_optimize/" _config.yml

hexo g && hexo deploy

# 关闭filter_optimize
sed -i "" "s/$open_filter_optimize/$close_filter_optimize/" _config.yml
```

wrote a script to solve this problem...

**Comment by ivan-nginx** [comment]
Guys, how something about `development` option?

**Comment by maple3142** [comment]
What about using `NODE_ENV`?

**Comment by daya0576** [comment]
> What about using `NODE_ENV`?

Maybe an option in config would be better, because in most cases, `hexo-filter-optimize` is not necessary for local developing.

**Comment by daya0576** [comment]
> What about using `NODE_ENV`?

Got ur idea, how can I manually set `NODE_ENV` locally? 
`export NODE_ENV=developing` and check it in code ?

**Comment by daya0576** [comment]
https://www.npmjs.com/package/hexo-filter-optimize
hi, can anyone publish the change of this MR?
