### ISSUE TITLE
这个有效么？为什么我弄了之后还起了反作用？

### ISSUE THREAD

**Issue by HuTsing** [theme-next/hexo-filter-optimize#6]
这是没用的时候，看红圈，一篇文章编译出来是40529个字符
![image](https://user-images.githubusercontent.com/25115173/40545868-f6b28ae0-605f-11e8-839c-3d8688f7b55e.png)
使用之后，看同一篇文章，有9万多个字符
![image](https://user-images.githubusercontent.com/25115173/40545966-4f3a6f20-6060-11e8-9238-bd0533749c9e.png)

**Comment by reuixiy** [comment]
有用，简直是神器啊，你可以试试将`enable`由`true`改为`false`，肉眼都能看出效果来:joy:，再加上 InstantClick 简直就无敌了！https://yixiuer.github.io/

**Comment by ghost** [comment]
我也是，用了之后速度好慢
