### ISSUE TITLE
js.excludes 参数是无效的

### ISSUE THREAD

**Issue by zhaojun1998** [theme-next/hexo-filter-optimize#7]
首先开启 `js.bundle` 后会导致 `Valine` 无法正确加载评论数和评论。
我试着排除 `Valine` 评论相关的 js, 发现使用 `js.excludes` 排除操作是无效的，对于任意的 js 文件都是如此。

**Comment by Gelomen** [comment]
+1，这个优化导致 hexo-tag-cloud 插件js失效，加入 excludes 也没用

**Comment by stevenjoezhang** [comment]
js.excludes 参数确实是无效的。可以升级到v0.2.7版本，valine的问题应该解决了。

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/hexo-filter-optimize/commit/273f63da1eb15186f6d519fc24944a6296007196
