### ISSUE TITLE
添加插件后fontawesome图标失效

### ISSUE THREAD

**Issue by liolok** [theme-next/hexo-filter-optimize#8]
这是添加插件的commit: https://github.com/liolok/liolok.github.io/commit/0f2d79f8e4bdcb2ca6b395cecdb95a92a5f525f4

这是问题截图:
![image](https://user-images.githubusercontent.com/34574198/41103723-685ecee2-6a9c-11e8-8135-b8b4d06cdead.png)

**Comment by anbuchelva** [comment]
i confirm the same. enabling css optimization breaks the font awesome icons.  Need help on the same.

Thanks!

**Comment by anbuchelva** [comment]
fixed it by adding this line ` - sed -i'' "s~../fonts/~lib/font-awesome/fonts/~g" themes/next/source/lib/font-awesome/css/font-awesome.min.css` in the [.travis.yml](https://github.com/anbuchelva/blog/blob/master/.travis.yml)

**Comment by liolok** [comment]
@anbuchelva as for me, i turned out to use gulp for compressing, but honestly I feel like all these methods(this module, [hexo-all-minifier](https://github.com/chenzhutian/hexo-all-minifier), and gulp-way) don't make my blog faster in Google's speed test.

**Comment by anbuchelva** [comment]
@liolok github pages doesn't cache your site, you can do it using cloudflare if you have a custom domain.  hexo-filter-optimize increased the page score from 70 to 99 for me. the 1% drop is caused by disqus, google analytics, webmaster tools etc.,

**Comment by liolok** [comment]
@anbuchelva you mean a high score in Google's speed test is based on both compressing and caching?:flushed:

**Comment by anbuchelva** [comment]
@liolok it depends; check your results the issues and solutions are provided by google.

**Comment by moeyui1** [comment]
In my case, I replace the fontawesome css file with CDN, which works for me. Edit `theme/next/_config.yml`
```
# Internal version: 4.6.2
# See: http://fontawesome.io/
fontawesome: https://cdn.bootcss.com/font-awesome/4.6.2/css/font-awesome.min.css
```

**Comment by ivan-nginx** [comment]
Similar to #2.

**Comment by stevenjoezhang** [comment]
See also https://www.guanqr.com/2019/08/20/speed-up-hexo/

<blockquote><img src="https://www.guanqr.com/2019/08/20/speed-up-hexo/0.png" width="48" align="right"><div><img src="/images/favicon-16x16.png?v=7.4.1" height="14"> 荷戟独彷徨</div><div><strong><a href="https://www.guanqr.com/2019/08/20/speed-up-hexo/index.html">加速 Hexo 博客的方法及遇到的问题</a></strong></div><div>由于我的博客部署在 GitHub Pages 上面，服务器在美国，在中国访问的话部分地区的加载速度比较慢。因此我在 6 月份的时候尝试使用 hexo-service-worker 与 hexo-filter-optimize 插件加速网站的访问速度。这两款插件确实对博客的加载速度有所帮助，但在当时我并没有留意博客内部的一些变化，直到最近，一个很严重的 BUG 暴露了出来。通过对插件的逐个排查，终于</div></blockquote>

**Comment by stevenjoezhang** [comment]
因为fontawesome加载字体用的是相对路径。懒得解决了，各位将就用吧。
